/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class ParamValueObjectImpl extends org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectTypeImpl implements org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObject
{
   public ParamValueObjectImpl()
   {
      super();
   }

   public ParamValueObjectImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("ParamValueObject", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public ParamValueObjectImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public ParamValueObjectImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
