/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public interface TestCaseType
{
   public void setRunInRegion(boolean value);

   public boolean isRunInRegion();

   public void setDescription(java.lang.String value);

   public java.lang.String getDescription();

   public void setName(java.lang.String value);

   public java.lang.String getName();

   public void setRunAscall(boolean value);

   public boolean isRunAscall();

   public void setStretchLayout(boolean value);

   public boolean isStretchLayout();

   public java.util.List getParamValueObject();

}

