/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class TestCaseTypeImpl extends oracle.xml.jaxb.JaxbNode implements org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseType
{
   public TestCaseTypeImpl()
   {
      super();
   }

   public TestCaseTypeImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("TestCase", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public TestCaseTypeImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TestCaseTypeImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setRunInRegion(boolean value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printBoolean(value);
      super.setJaxbAttr("runInRegion", "", lexval);
   }

   public boolean isRunInRegion()
   {
      java.lang.String lexval = super.getJaxbAttr("runInRegion", "");
      boolean value = oracle.xml.jaxb.JaxbDatatypeConverter.parseBoolean(lexval);
      return value == false ? true : value;
   }

   public void setDescription(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("description", "", lexval);
   }

   public java.lang.String getDescription()
   {
      java.lang.String lexval = super.getJaxbAttr("description", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setName(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("name", "", lexval);
   }

   public java.lang.String getName()
   {
      java.lang.String lexval = super.getJaxbAttr("name", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setRunAscall(boolean value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printBoolean(value);
      super.setJaxbAttr("runAscall", "", lexval);
   }

   public boolean isRunAscall()
   {
      java.lang.String lexval = super.getJaxbAttr("runAscall", "");
      boolean value = oracle.xml.jaxb.JaxbDatatypeConverter.parseBoolean(lexval);
      return value == false ? false : value;
   }

   public void setStretchLayout(boolean value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printBoolean(value);
      super.setJaxbAttr("stretchLayout", "", lexval);
   }

   public boolean isStretchLayout()
   {
      java.lang.String lexval = super.getJaxbAttr("stretchLayout", "");
      boolean value = oracle.xml.jaxb.JaxbDatatypeConverter.parseBoolean(lexval);
      return value == false ? true : value;
   }

   public java.util.List getParamValueObject()
   {
      return (java.util.List)super.getList("ParamValueObject", "http://adf.emg.org/tftester", this, 0);
   }

   public Object createJaxbNode(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name = node.getLocalName();
      java.lang.String namespace = node.getNamespaceURI();
      if (namespace == null)
         namespace = "";

      if (name.equals("ParamValueObject") && namespace.equals("http://adf.emg.org/tftester"))
      {
         org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectTypeImpl obj = new org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectTypeImpl((oracle.xml.parser.v2.XMLElement)node);
         return obj;
      }

      return super.createJaxbNode(node);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("ParamValueObject") && namespace.equals("http://adf.emg.org/tftester"))
            {
               super.setNodeVectorValue("ParamValueObject", "http://adf.emg.org/tftester", this, 0, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   protected static final Object[] _ParamValueObject = 
   {};

   protected static final Object[] _TestCaseType = 
   {_ParamValueObject };

   protected Object[] getSchemaObject()
   {
      return _TestCaseType;
   }

}
