/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class ObjectFactory 
{
   public org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseType createTestCaseType()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseType elem = new org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseTypeImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTester createTaskFlowTester()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTester elem = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlow createTaskFlow()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlow elem = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowType createTaskFlowType()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowType elem = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTypeImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObject createParamValueObject()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObject elem = new org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.TestCase createTestCase()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.TestCase elem = new org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterType createTaskFlowTesterType()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterType elem = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterTypeImpl(ownerDocument);
      return elem;
   }

   public org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectType createParamValueObjectType()
   {
      org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectType elem = new org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectTypeImpl(ownerDocument);
      return elem;
   }

   public Object newInstance (Class javaContentInterface) throws javax.xml.bind.JAXBException
   {
      Object newInstance = null;
      java.lang.String elemName = javaContentInterface.getName();
      try
      {
         if (elemName.equals("org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTester"))
         {
            newInstance = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlow"))
         {
            newInstance = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObject"))
         {
            newInstance = new org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectImpl(ownerDocument);
            return newInstance;
         }
         if (elemName.equals("org.emg.adf.tftester.rt.model.xml.jaxb.TestCase"))
         {
            newInstance = new org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseImpl(ownerDocument);
            return newInstance;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.JAXBException(e.toString());
      }
      return null;
   }

   public Object getProperty(String name)
   {
      return null;
   }

   public void setProperty(String name, Object value)
   {
   }

   public Object unmarshal(org.w3c.dom.Node node) throws javax.xml.bind.UnmarshalException
   {
      java.lang.String elemName = node.getLocalName();
      try
      {
         if (elemName.equals("TaskFlowTester"))
         {
            org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTester unode = 
                 new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("TaskFlow"))
         {
            org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlow unode = 
                 new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("ParamValueObject"))
         {
            org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObject unode = 
                 new org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
         if (elemName.equals("TestCase"))
         {
            org.emg.adf.tftester.rt.model.xml.jaxb.TestCase unode = 
                 new org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseImpl((oracle.xml.parser.v2.XMLElement)node);
            return unode;
         }
      }
      catch (Exception e)
      {
         throw new javax.xml.bind.UnmarshalException(e.toString());
      }
      return null;
   }

   public void setOwnerDocument(oracle.xml.parser.v2.XMLDocument doc)
   {
      ownerDocument = doc;
   }


   public oracle.xml.parser.v2.XMLDocument getOwnerDocument()
   {
      return ownerDocument;
   }

   public Object getSchemaLocation() throws Exception
   {
      return new java.io.File("K:/adfemg/TaskFlowTester/TaskFlowTesterRT/ViewController/src/org/emg/adf/tftester/rt/model/xml/tftester.xsd").toURL();
   }

   private oracle.xml.parser.v2.XMLDocument ownerDocument = 
        new oracle.xml.parser.v2.XMLDocument();

}
