/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class TaskFlowTesterTypeImpl extends oracle.xml.jaxb.JaxbNode implements org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterType
{
   public TaskFlowTesterTypeImpl()
   {
      super();
   }

   public TaskFlowTesterTypeImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("TaskFlowTester", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public TaskFlowTesterTypeImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TaskFlowTesterTypeImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public java.util.List getTaskFlow()
   {
      return (java.util.List)super.getList("TaskFlow", "http://adf.emg.org/tftester", this, 0);
   }

   public Object createJaxbNode(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name = node.getLocalName();
      java.lang.String namespace = node.getNamespaceURI();
      if (namespace == null)
         namespace = "";

      if (name.equals("TaskFlow") && namespace.equals("http://adf.emg.org/tftester"))
      {
         org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTypeImpl obj = new org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTypeImpl((oracle.xml.parser.v2.XMLElement)node);
         return obj;
      }

      return super.createJaxbNode(node);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("TaskFlow") && namespace.equals("http://adf.emg.org/tftester"))
            {
               super.setNodeVectorValue("TaskFlow", "http://adf.emg.org/tftester", this, 0, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   protected static final Object[] _TaskFlow = 
   {};

   protected static final Object[] _TaskFlowTesterType = 
   {_TaskFlow };

   protected Object[] getSchemaObject()
   {
      return _TaskFlowTesterType;
   }

}
