/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public interface ParamValueObjectType
{
   public void setName(java.lang.String value);

   public java.lang.String getName();

   public void setClassName(java.lang.String value);

   public java.lang.String getClassName();

   public void setValueAsString(java.lang.String value);

   public java.lang.String getValueAsString();

   public java.util.List getParamValueObject();

}

