/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class ParamValueObjectTypeImpl extends oracle.xml.jaxb.JaxbNode implements org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectType
{
   public ParamValueObjectTypeImpl()
   {
      super();
   }

   public ParamValueObjectTypeImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("ParamValueObject", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public ParamValueObjectTypeImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public ParamValueObjectTypeImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setName(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("name", "", lexval);
   }

   public java.lang.String getName()
   {
      java.lang.String lexval = super.getJaxbAttr("name", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setClassName(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("className", "", lexval);
   }

   public java.lang.String getClassName()
   {
      java.lang.String lexval = super.getJaxbAttr("className", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setValueAsString(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("valueAsString", "", lexval);
   }

   public java.lang.String getValueAsString()
   {
      java.lang.String lexval = super.getJaxbAttr("valueAsString", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public java.util.List getParamValueObject()
   {
      return (java.util.List)super.getList("ParamValueObject", "http://adf.emg.org/tftester", this, 0);
   }

   public Object createJaxbNode(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name = node.getLocalName();
      java.lang.String namespace = node.getNamespaceURI();
      if (namespace == null)
         namespace = "";

      if (name.equals("ParamValueObject") && namespace.equals("http://adf.emg.org/tftester"))
      {
         org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectTypeImpl obj = new org.emg.adf.tftester.rt.model.xml.jaxb.ParamValueObjectTypeImpl((oracle.xml.parser.v2.XMLElement)node);
         return obj;
      }

      return super.createJaxbNode(node);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("ParamValueObject") && namespace.equals("http://adf.emg.org/tftester"))
            {
               super.setNodeVectorValue("ParamValueObject", "http://adf.emg.org/tftester", this, 0, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   protected static final Object[] _ParamValueObject = 
   {};

   protected static final Object[] _ParamValueObjectType = 
   {_ParamValueObject };

   protected Object[] getSchemaObject()
   {
      return _ParamValueObjectType;
   }

}
