/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public interface TaskFlowTester extends org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterType, javax.xml.bind.Element
{
}

