/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class TaskFlowImpl extends org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTypeImpl implements org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlow
{
   public TaskFlowImpl()
   {
      super();
   }

   public TaskFlowImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("TaskFlow", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public TaskFlowImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TaskFlowImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
