/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class TestCaseImpl extends org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseTypeImpl implements org.emg.adf.tftester.rt.model.xml.jaxb.TestCase
{
   public TestCaseImpl()
   {
      super();
   }

   public TestCaseImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("TestCase", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public TestCaseImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TestCaseImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
