/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class TaskFlowTesterImpl extends org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTesterTypeImpl implements org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowTester
{
   public TaskFlowTesterImpl()
   {
      super();
   }

   public TaskFlowTesterImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("TaskFlowTester", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public TaskFlowTesterImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TaskFlowTesterImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

}
