/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public interface TaskFlowType
{
   public void setTaskFlowId(java.lang.String value);

   public java.lang.String getTaskFlowId();

   public void setDisplayName(java.lang.String value);

   public java.lang.String getDisplayName();

   public java.util.List getTestCase();

}

