/* DO NOT EDIT THIS FILE - This file was generated by     */
/* Oracle JAXB Class Generator Implementation.            */
/* Any Modification to this file will be lost upon        */
/* recompilation of source schema                         */ 

package org.emg.adf.tftester.rt.model.xml.jaxb;


public class TaskFlowTypeImpl extends oracle.xml.jaxb.JaxbNode implements org.emg.adf.tftester.rt.model.xml.jaxb.TaskFlowType
{
   public TaskFlowTypeImpl()
   {
      super();
   }

   public TaskFlowTypeImpl(oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super("TaskFlow", "http://adf.emg.org/tftester", ownerDoc); 
   }

   public TaskFlowTypeImpl(java.lang.String name, java.lang.String namespace, oracle.xml.parser.v2.XMLDocument ownerDoc)
   {
      super(name, namespace, ownerDoc);
   }

   public TaskFlowTypeImpl(oracle.xml.parser.v2.XMLElement node)
   {
      super(node);
   }

   public void setTaskFlowId(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("taskFlowId", "", lexval);
   }

   public java.lang.String getTaskFlowId()
   {
      java.lang.String lexval = super.getJaxbAttr("taskFlowId", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public void setDisplayName(java.lang.String value)
   {
      java.lang.String lexval = oracle.xml.jaxb.JaxbDatatypeConverter.printString(value);
      super.setJaxbAttr("displayName", "", lexval);
   }

   public java.lang.String getDisplayName()
   {
      java.lang.String lexval = super.getJaxbAttr("displayName", "");
      return oracle.xml.jaxb.JaxbDatatypeConverter.parseString(lexval);
   }

   public java.util.List getTestCase()
   {
      return (java.util.List)super.getList("TestCase", "http://adf.emg.org/tftester", this, 0);
   }

   public Object createJaxbNode(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name = node.getLocalName();
      java.lang.String namespace = node.getNamespaceURI();
      if (namespace == null)
         namespace = "";

      if (name.equals("TestCase") && namespace.equals("http://adf.emg.org/tftester"))
      {
         org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseTypeImpl obj = new org.emg.adf.tftester.rt.model.xml.jaxb.TestCaseTypeImpl((oracle.xml.parser.v2.XMLElement)node);
         return obj;
      }

      return super.createJaxbNode(node);
   }

   public void populateNodeArray(oracle.xml.parser.v2.XMLNode node)
   {
      java.lang.String name, namespace;
      oracle.xml.parser.v2.XMLNode n = (oracle.xml.parser.v2.XMLNode)node.getFirstChild();

      int i = 0;
      while (n != null)
      {
         name = n.getLocalName(); 
         namespace = n.getNamespaceURI();

         if (name == null)
         {
            n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
            i++;
            continue;
         }

         if (namespace == null)
            namespace = "";

         if (name != null)
         {
            if (name.equals("TestCase") && namespace.equals("http://adf.emg.org/tftester"))
            {
               super.setNodeVectorValue("TestCase", "http://adf.emg.org/tftester", this, 0, n);
            }

         }
         n = (oracle.xml.parser.v2.XMLNode)n.getNextSibling();
         i++;
      }

      super.populateNodeArray(node);
   }

   protected static final Object[] _TestCase = 
   {};

   protected static final Object[] _TaskFlowType = 
   {_TestCase };

   protected Object[] getSchemaObject()
   {
      return _TaskFlowType;
   }

}
